#!/bin/sh
. /lib/functions.sh

apply_config() {
	local plugin_name="$1"
	local container_name="$2"
	config_get init "$1" init
	config_get exec "$1" exec
	config_get test "$1" test

	echo "$2" > "/var/run/luci-reload-status"

	[ -n "$init" ] && reload_init "$2" "$init" "$container_name" "$test"
	[ -n "$exec" ] && reload_exec "$2" "$exec" "$container_name" "$test"
}

reload_exec() {
	local service="$1"
	local container_name="$3"
	local ok="$4"
	set -- $2
	local cmd="$1"; shift
	
	[ -x "$cmd" ] && {
		echo "Reloading $service... "
		( $cmd "$container_name" "$@") 2>/dev/null 1>&2
		[ -n "$ok" -a "$?" != "$ok" ] && echo '!!! Failed to reload' $service '!!!'
	}
}

reload_init() {
	local container_name="$3"
	[ -x /etc/init.d/$2 ] && {
		echo "Reloading $1... "
		/etc/init.d/$2 "$container_name" reload >/dev/null 2>&1
		[ -n "$4" -a "$?" != "$4" ] && echo '!!! Failed to reload' $1 '!!!'
	}
}

lock "/var/run/luci-reload"

config_load ucitrack

for i in $*; do
	plugin_name=$(echo $i | awk -F':' '{print $1}')
	container_name=$(echo $i | awk -F':' '{print $2}')
	config_foreach apply_config $plugin_name $container_name
done

rm -f "/var/run/luci-reload-status"
lock -u "/var/run/luci-reload"
